version: "3.8"

services:
  breathecode:
    image: geeksacademy/breathecode:development
    env_file:
      - ./.env
    environment:
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgres://user:pass@postgres:5432/breathecode
      - CELERY_DISABLE_SCHEDULER=
      - ALLOW_UNSAFE_CYPRESS_APP=True
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis

  bc-dev:
    build:
      context: .
      dockerfile: .dev.Dockerfile
    volumes:
      - ./:/home/shell/apiv2
    environment:
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgres://user:pass@postgres:5432/breathecode
      - CELERY_DISABLE_SCHEDULER=
      - ALLOW_UNSAFE_CYPRESS_APP=True
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=breathecode
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - postgres

volumes:
  postgres_data:
