site_name: BreatheCode
site_url: https://breathecode.herokuapp.com/

theme:
  name: "material"

# this define the order of menu
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import os
            - import django
            - os.environ.setdefault("DJANGO_SETTINGS_MODULE", "breathecode.settings")
            - django.setup()

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
